[package]
categories = ["api-bindings"]
description = "OpenTelemetry v1 API binding based on tonic/prost."
documentation = "https://github.com/tremor-rs/otelapis"
edition = "2021"
exclude = ["*.sh"]
keywords = ["opentelemetry", "api", "grpc", "protobuf", "tremor"]
license = "Apache-2.0"
name = "tremor-otelapis"
readme = "README.md"
repository = "https://github.com/tremor-rs/tremor-otelapis"
version = "0.5.0"
authors = ["The Tremor Team"]

[lib]
doctest = false

[package.metadata.docs.rs]
all-features = true

[dependencies]
prost = { version = "0.13", default-features = false, features = [
    "std",
    "derive",
] }
tokio = { version = "1.40.0", optional = true, default-features = false, features = [
    "sync",
] }
tonic = { version = "0.12", default-features = false, features = [
    "transport",
    "codegen",
    "prost",
] }

[build-dependencies]
tonic-build = { version = "0.12" }

[features]

# Default - all
default = ["otel-all", "gzip", "zstd", "tls"]

# Enable channel abstraction
channels = ["dep:tokio"]

# Enable gzip compression support
gzip = ["tonic/gzip"]
# Enable zstd compression support
zstd = ["tonic/zstd"]
# Enable tls support
tls = ["tonic/tls", "tonic/tls-webpki-roots"]

# Generated from .proto definitions
opentelemetry-proto-collector-logs-v1 = []
opentelemetry-proto-collector-metrics-v1 = []
opentelemetry-proto-collector-trace-v1 = []
opentelemetry-proto-common-v1 = []
opentelemetry-proto-logs-v1 = []
opentelemetry-proto-metrics-v1 = []
opentelemetry-proto-resource-v1 = []
opentelemetry-proto-trace-v1 = []

# Convenience
otel-gen = [
    "opentelemetry-proto-resource-v1",
    "opentelemetry-proto-common-v1",
    "opentelemetry-proto-logs-v1",
    "opentelemetry-proto-collector-logs-v1",
    "opentelemetry-proto-metrics-v1",
    "opentelemetry-proto-trace-v1",
    "opentelemetry-proto-collector-metrics-v1",
    "opentelemetry-proto-collector-trace-v1",
]

otel-all = [
    "otel-logs",
    "otel-metrics",
    "otel-trace",
    "opentelemetry-proto-resource-v1",
    "opentelemetry-proto-common-v1",
    "opentelemetry-proto-logs-v1",
    "opentelemetry-proto-collector-logs-v1",
    "opentelemetry-proto-metrics-v1",
    "opentelemetry-proto-trace-v1",
    "opentelemetry-proto-collector-metrics-v1",
    "opentelemetry-proto-collector-trace-v1",
]

otel-logs = [
    "opentelemetry-proto-resource-v1",
    "opentelemetry-proto-common-v1",
    "opentelemetry-proto-logs-v1",
    "opentelemetry-proto-collector-logs-v1",
]

otel-metrics = [
    "opentelemetry-proto-resource-v1",
    "opentelemetry-proto-common-v1",
    "opentelemetry-proto-metrics-v1",
    "opentelemetry-proto-collector-metrics-v1",
]

otel-trace = [
    "opentelemetry-proto-resource-v1",
    "opentelemetry-proto-common-v1",
    "opentelemetry-proto-trace-v1",
    "opentelemetry-proto-collector-trace-v1",
]
