name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Update deps
        run: sudo apt-get update -y
      - name: Install deps [Linux]
        run: sudo apt-get install -y libssl-dev libssl1.0
      - uses: actions-rs/toolchain@v1
        with:
          override: true
          profile: minimal
          toolchain: stable
      - name: Run tests
        run: cargo test --all